FROM openresty/openresty:alpine

RUN apk add --no-cache luarocks5.3 \
    && luarocks-5.3 install lua-resty-jwt

COPY nginx/main.conf /usr/local/openresty/nginx/conf/nginx.conf
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
